apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"minio"},"name":"guestbook-ui","namespace":"minio"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"guestbook-ui"}}}
    labels:
      app.kubernetes.io/instance: minio
    name: guestbook-ui
    namespace: minio
  spec:
    clusterIP: 10.100.113.38
    clusterIPs:
    - 10.100.113.38
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: guestbook-ui
    sessionAffinity: None
    type: ClusterIP
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"minio-api","namespace":"minio"},"spec":{"ports":[{"nodePort":30900,"port":9000,"targetPort":9000}],"selector":{"app":"minio"},"type":"NodePort"}}
      metallb.universe.tf/ip-allocated-from-pool: first-pool
    name: minio-api
    namespace: minio
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.102.136.171
    clusterIPs:
    - 10.102.136.171
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30900
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: minio
    sessionAffinity: None
    type: LoadBalancer
    loadBalancer:
      ingress:
      - ip: 172.16.16.201
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"minio-console","namespace":"minio"},"spec":{"ports":[{"nodePort":30901,"port":9001,"targetPort":9001}],"selector":{"app":"minio"},"type":"NodePort"}}
      metallb.universe.tf/ip-allocated-from-pool: first-pool
    name: minio-console
    namespace: minio
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.98.63.16
    clusterIPs:
    - 10.98.63.16
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30901
      port: 9001
      protocol: TCP
      targetPort: 9001
    selector:
      app: minio
    sessionAffinity: None
    type: LoadBalancer
    loadBalancer:
      ingress:
      - ip: 172.16.16.202
kind: List
metadata:
