apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"mlflow","namespace":"mlflow"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mlflow"}},"template":{"metadata":{"labels":{"app":"mlflow"}},"spec":{"containers":[{"command":["/bin/bash","-c","pip install mlflow psycopg2-binary boto3\nmlflow server             --host 0.0.0.0             --port 5000             --backend-store-uri postgresql://mlflowuser:mlflowpassword@postgres-postgresql.postgres:5432/mlflowdb             --default-artifact-root s3://mlflow-artifacts/\n"],"env":[{"name":"MLFLOW_S3_ENDPOINT_URL","value":"http://172.16.16.215:30900"},{"name":"AWS_ACCESS_KEY_ID","value":"minioadmin"},{"name":"AWS_SECRET_ACCESS_KEY","value":"minioadmin123"},{"name":"MLFLOW_S3_IGNORE_TLS","value":"true"}],"image":"python:3.9-slim","name":"mlflow","ports":[{"containerPort":5000}]}]}}}}
  generation: 1
  name: mlflow
  namespace: mlflow
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mlflow
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          pip install mlflow psycopg2-binary boto3
          mlflow server             --host 0.0.0.0             --port 5000             --backend-store-uri postgresql://mlflowuser:mlflowpassword@postgres-postgresql.postgres:5432/mlflowdb             --default-artifact-root s3://mlflow-artifacts/
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://172.16.16.215:30900
        - name: AWS_ACCESS_KEY_ID
          value: minioadmin
        - name: AWS_SECRET_ACCESS_KEY
          value: minioadmin123
        - name: MLFLOW_S3_IGNORE_TLS
          value: "true"
        image: python:3.9-slim
        imagePullPolicy: IfNotPresent
        name: mlflow
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-06-10T09:13:57Z"
    lastUpdateTime: "2026-06-10T09:13:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    type: Available
  - lastTransitionTime: "2026-06-10T09:13:46Z"
    lastUpdateTime: "2026-06-10T09:13:57Z"
    message: ReplicaSet "mlflow-7dd564c84d" has successfully progressed.
    reason: NewReplicaSetAvailable
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
