apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

bases:
- ../../bases/minio

patches:
- path: minio-replicas.yaml

commonLabels:
  environment: production
  version: v1
