apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - minio/
  - postgres/
  - mlflow/
  - argocd/

commonLabels:
  managed-by: kustomize
  stack: mlops

configMapGenerator:
- name: mlops-config
  literals:
  - environment=production
  - version=1.0.0
